version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "large" 
 
    steps:
      - checkout      
      - run: .\1.ps1
      - run: .\2.ps1
      - run: ping -n 999999 10.10.10.10
